name: First Worflow
on : push
jobs: 
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name : Print Greeting
        run : echo "Hello World"

      - name : print goodby
        run : echo "Bye World"
